# Generated by Django 5.2.12 on 2026-04-14 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('escrow', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paystack', 'Paystack')], default='paystack', max_length=30)),
                ('reference', models.CharField(db_index=True, max_length=120, unique=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('status', models.CharField(choices=[('initialized', 'Initialized'), ('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='initialized', max_length=20)),
                ('authorization_url', models.URLField(blank=True, null=True)),
                ('gateway_metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment_records', to='escrow.escrowtransaction')),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_1764ff_idx'), models.Index(fields=['provider'], name='payments_pa_provide_2ba189_idx'), models.Index(fields=['escrow'], name='payments_pa_escrow__a94c27_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payment_amount_gt_zero')],
            },
        ),
        migrations.CreateModel(
            name='PayoutRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=120, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payout_records', to='escrow.escrowtransaction')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_payouts', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='payments_pa_status_cc8e2e_idx'), models.Index(fields=['escrow'], name='payments_pa_escrow__3b540b_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='payout_amount_gt_zero')],
            },
        ),
        migrations.CreateModel(
            name='RefundRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(db_index=True, max_length=120, unique=True)),
                ('provider_reference', models.CharField(blank=True, max_length=150, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('success', 'Success'), ('failed', 'Failed'), ('reversed', 'Reversed')], default='pending', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('escrow', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='refund_records', to='escrow.escrowtransaction')),
                ('initiated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiated_refunds', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='payments_re_status_29b51f_idx'), models.Index(fields=['escrow'], name='payments_re_escrow__46afb3_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='refund_amount_gt_zero')],
            },
        ),
    ]
