# Generated by Django 5.2.12 on 2026-04-14 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaystackWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.CharField(max_length=80)),
                ('event_id', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('reference', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('payload_hash', models.CharField(db_index=True, max_length=64, unique=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('processed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['event'], name='payments_pa_event_dd77a6_idx'), models.Index(fields=['reference'], name='payments_pa_referen_c963e0_idx'), models.Index(fields=['processed'], name='payments_pa_process_a66c95_idx')],
            },
        ),
    ]
