# Generated by Django 5.2.12 on 2026-04-14 10:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_paystackwebhookevent'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SellerPayoutDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('paystack', 'Paystack')], default='paystack', max_length=30)),
                ('bank_code', models.CharField(max_length=20)),
                ('account_number', models.CharField(max_length=30)),
                ('account_name', models.CharField(blank=True, max_length=120)),
                ('currency', models.CharField(default='NGN', max_length=10)),
                ('recipient_code', models.CharField(blank=True, db_index=True, max_length=120, null=True)),
                ('recipient_reference', models.CharField(blank=True, max_length=150, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='seller_payout_detail', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['provider'], name='payments_se_provide_a074a1_idx'), models.Index(fields=['recipient_code'], name='payments_se_recipie_e881dc_idx'), models.Index(fields=['is_active'], name='payments_se_is_acti_2d2ede_idx')],
            },
        ),
    ]
