# Generated by Django 5.2.12 on 2026-04-14 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disputes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dispute',
            name='resolution_outcome',
            field=models.CharField(blank=True, choices=[('release', 'Release Funds'), ('refund', 'Refund Buyer')], max_length=20, null=True),
        ),
    ]
