# Generated by Django 5.2.12 on 2026-04-14 16:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('listing_created', 'Listing Created'), ('escrow_created', 'Escrow Created'), ('payment_initialized', 'Payment Initialized'), ('payment_verified', 'Payment Verified'), ('escrow_funded', 'Escrow Funded'), ('release_triggered', 'Release Triggered'), ('payout_executed', 'Payout Executed'), ('refund_triggered', 'Refund Triggered'), ('dispute_opened', 'Dispute Opened'), ('dispute_resolved', 'Dispute Resolved')], db_index=True, max_length=64)),
                ('object_type', models.CharField(db_index=True, max_length=64)),
                ('object_id', models.PositiveBigIntegerField(blank=True, db_index=True, null=True)),
                ('object_ref', models.CharField(db_index=True, max_length=255)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['action'], name='core_auditl_action_d9fb24_idx'), models.Index(fields=['object_type', 'object_id'], name='core_auditl_object__42e4a9_idx'), models.Index(fields=['created_at'], name='core_auditl_created_dc23ea_idx')],
            },
        ),
    ]
