# Generated by Django 5.2.12 on 2026-04-14 09:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EscrowTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('title_snapshot', models.CharField(max_length=200)),
                ('description_snapshot', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('payment_pending', 'Payment Pending'), ('funded', 'Funded'), ('released', 'Released'), ('refunded', 'Refunded'), ('disputed', 'Disputed'), ('cancelled', 'Cancelled'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('buyer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='buyer_escrows', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='escrow_transactions', to='listings.listing')),
                ('seller', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seller_escrows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('-created_at',),
                'indexes': [models.Index(fields=['status'], name='escrow_escr_status_9ea6b9_idx'), models.Index(fields=['buyer'], name='escrow_escr_buyer_i_ef21f3_idx'), models.Index(fields=['seller'], name='escrow_escr_seller__80b509_idx'), models.Index(fields=['listing'], name='escrow_escr_listing_3b1615_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(('amount__gt', 0)), name='escrow_amount_gt_zero'), models.CheckConstraint(condition=models.Q(('buyer', models.F('seller')), _negated=True), name='escrow_buyer_not_seller')],
            },
        ),
    ]
